var appConstants = {
  JOIN_ROOM: 'JOIN_ROOM',
  START_LOCAL_CONN: 'START_LOCAL_CONN',
  START_REMOTE_CONN: 'START_REMOTE_CONN',
  STOP_REMOTE_CONN: 'STOP_REMOTE_CONN',
  SEND_TEXT_MESSAGE: 'SEND_TEXT_MESSAGE',
  SET_EMPLOYEE_DATA: 'SET_EMPLOYEE_DATA'
};

module.exports = appConstants;
